apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: test-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-replicaset
  template:
    metadata:
      labels:
        app: test-replicaset
    spec:
      containers:
      - name: test-replicaset
        image: rozen88/test

