apiVersion: v1
kind: ReplicationController
metadata:
  name: test-change-label
spec:
  replicas: 3
  selector:
    app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: test-change-label
        image: rozen88/test
        ports:
        - containerPort: 8080
