apiVersion: v1
kind: Pod
metadata:
  name: test-liveness-v2
spec:
  containers:
  - image: rozen88/test_error
    name: test-error-v2
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
